server_connect_timeout: 5000
listeners:
- query_port: 2500
  motd: '&aBungeeCord Sunucu'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 0
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.send
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.find
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  Notch:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 50ee1253-1723-44fc-a716-ec89c0c7bd55
online_mode: false
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  FakeLobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 0.0.0.0:25000
    restricted: false
  Lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 0.0.0.0:25001
    restricted: false
  Oyun:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 0.0.0.0:25002
    restricted: false
